export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENT = 'SET_INGREDIENT';
export const FETCH_INGREDIENT_FAILED = 'FETCH_INGREDIENT_FAILED';
export const BURGER_ORDER_START = 'BURGER_ORDER_START';
export const BURGER_ORDER_SUCCESS = 'BURGER_ORDER_SUCCESS';
export const BURGER_ORDER_FAILED = 'BURGER_ORDER_FAILED';
